// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_w9ldYkRLB3SIcciWY0hS4TcYGtxDtI4',
    appId: '1:1068368481104:android:564c1b524bd124788f7a55',
    messagingSenderId: '1068368481104',
    projectId: 'voyixi',
    storageBucket: 'voyixi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRRGkistFz80eItSEKtrBSdJMrf6gpckE',
    appId: '1:1068368481104:ios:83a448cce355d1d88f7a55',
    messagingSenderId: '1068368481104',
    projectId: 'voyixi',
    storageBucket: 'voyixi.firebasestorage.app',
    androidClientId: '1068368481104-kdqvau6a9gs82a50963k9h5gm2te1bo3.apps.googleusercontent.com',
    iosClientId: '1068368481104-qet6g7gu3h5e0olhqffgdrpkn4c2uamb.apps.googleusercontent.com',
    iosBundleId: 'com.voyixi.voyixi',
  );
}
