import 'package:flutter/material.dart';
import '../widgets/navigation_bar.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF0FAFA), // Voyixi genel temana uygun açık arka plan
      appBar: AppBar(
        title: const Text('Privacy & Terms', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
        backgroundColor: const Color(0xFF0DA3A3), // Ana logonun rengi
        foregroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 18),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSection('1. Privacy Policy', 
              'Your privacy is important to us. Voyixi uses your location data to provide real-time travel recommendations and generate custom tour itineraries via AI services. Your data is securely stored and never shared with third parties.'),
            const SizedBox(height: 20),
            _buildSection('2. Terms of Service', 
              'By using the Voyixi mobile application, you agree to comply with and be bound by these terms. The travel routes generated by our AI system are for informational and recreational purposes. Users are responsible for checking local conditions, safety, and operational hours of the recommended venues.'),
            const SizedBox(height: 20),
            _buildSection('3. Account & Security', 
              'As a user, you are responsible for maintaining the confidentiality of your authentication details linked with Firebase. Voyixi holds no liability for unauthorized access resulting from personal negligence.'),
            const SizedBox(height: 40),
            Center(
              child: Text(
                'Last Updated: May 2026',
                style: TextStyle(color: Colors.grey[500], fontSize: 11, fontStyle: FontStyle.italic),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(fontSize: 15, fontWeight: FontWeight.bold, color: Color(0xFF1A2E2E)),
        ),
        const SizedBox(height: 8),
        Text(
          content,
          style: const TextStyle(fontSize: 13, color: Color(0xFF4A6060), height: 1.5),
        ),
      ],
    );
  }
}